### ISSUE TITLE
Lab_3/pygame_test.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-006/gribova#2]
1) См. правила оформления докстрингов https://www.python.org/dev/peps/pep-0257/
2) Такие штуки
`for i in range(len(birds)):
        draw_bird(birds[i][0],birds[i][1],birds[i][2]) `
можно делать проще, например
`for x, y, a in birds:
        draw_bird(x, y, a)`
Он сразу разобьет очередные элементы `bird[:]` и положит их в `x, y, a`
3) Проблемы с PEP8
4) Почему?:)
`#I HATE this STUff`

**Comment by gribovanika** [comment]
i tryed to solve these problems. I don't know what to do else there... if not tell me)
